name: Sync fork-test Upstream

env:
  # Required, URL to upstream (fork base)
  UPSTREAM_URL: "https://github.com/sam-orevillestudios/fork-test.git"
   # Workflow Token
  WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  # Optional, defaults to main
  UPSTREAM_BRANCH: "main"
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: "main"
  # Optional merge arguments
  REBASE_ARGS: "-Xtheirs"
  EMAIL: "sam@orevillestudios.com"
  NAME: "Sam Diefenbacher"

on:
  workflow_dispatch:

# Jobs
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Sync and rebase upstream repository with current repository
        run: |
          # Set git config email and username 
          git config --global user.email ${{env.EMAIL}}
          git config --global user.name ${{env.NAME}}

          # Set upstream url if we don't have one
          git remote add upstream ${{env.UPSTREAM_URL}}

          # Fetch upstream origin
          git fetch upstream

          # Rebase changse and apply our commits on top
          git rebase upstream/${{env.UPSTREAM_BRANCH}} ${{env.REBASE_ARGS}}