name: Sync fork-test Upstream

env:
  # Required, URL to upstream (fork base)
  UPSTREAM_URL: "https://github.com/sam-orevillestudios/fork-test.git"
  # Optional, defaults to main
  UPSTREAM_BRANCH: "main"
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: "main"
  # Optional merge arguments
  REBASE_ARGS: "-Xtheirs"

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# Jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Sync and rebase upstream repository with current repository
        run: |
          # Set upstream url if we don't have one
          git remote set-url origin ${{env.UPSTREAM_URL}}
          # Fetch upstream origin
          git fetch upstream/origin
          # Rebase changse and apply our commits on top
          git rebase upstream/${{env.UPSTREAM_BRANCH}} ${{env.REBASE_ARGS}}